package com.lightsound.backend.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@Entity
@Table(name = "attempt_records")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AttemptRecord {

    @Id
    @Column(name = "session_id")
    private String sessionId; // session ID generated by client/server (UUID)

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @Column(name = "course_id", nullable = false)
    private String courseId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lesson_id", nullable = false)
    private Lesson lesson;

    @Builder.Default
    private Integer score = 0;

    @Column(name = "total_correct_answer")
    @Builder.Default
    private Integer totalCorrectAnswer = 0;

    @Column(name = "completion_time")
    @Builder.Default
    private Integer completionTime = 0; // duration in seconds

    @Column(name = "completed_at")
    @Builder.Default
    private LocalDateTime completedAt = LocalDateTime.now();

    @Convert(converter = JsonListConverter.class)
    @Column(name = "answered_questions", columnDefinition = "TEXT")
    @Builder.Default
    private List<Map<String, Object>> answeredQuestions = new ArrayList<>();

    @Column(name = "is_completed")
    @Builder.Default
    private Boolean isCompleted = false;
}
